export function buildSummarizerPrompt(input: string): string {
  return [
    "You are a structured report generator.",
    "Output STRICT JSON ONLY.",
    "Do not output markdown, prose, code fences, or extra text.",
    "Use EXACT schema keys and no extra keys:",
    "{",
    '  "title": string,',
    '  "tlDr": string[],',
    '  "keyInsights": string[],',
    '  "comparisonTable": [{ "tool": string, "bestFor": string, "pricing": string, "strength": string }],',
    '  "analysis": [{ "tool": string, "summary": string }],',
    '  "pricingSummary": string[],',
    '  "prosCons": [{ "tool": string, "pros": string[], "cons": string[] }],',
    '  "finalRecommendation": string',
    "}",
    "Rules:",
    "- No extra keys.",
    "- No empty arrays; use best-effort placeholders when data is weak.",
    "- Keep text concise and readable.",
    "- Max 5 items per list.",
    "- If pricing is unknown, use 'Unknown'.",
    "",
    "JSON skeleton example:",
    "{",
    '  "title": "",',
    '  "tlDr": ["", "", ""],',
    '  "keyInsights": ["", "", ""],',
    '  "comparisonTable": [',
    '    { "tool": "", "bestFor": "", "pricing": "", "strength": "" }',
    "  ],",
    '  "analysis": [',
    '    { "tool": "", "summary": "" }',
    "  ],",
    '  "pricingSummary": ["", ""],',
    '  "prosCons": [',
    '    { "tool": "", "pros": [""], "cons": [""] }',
    "  ],",
    '  "finalRecommendation": ""',
    "}",
    "",
    "Source input:",
    input,
  ].join("\n");
}
